# Generated by Django 2.1.2 on 2019-02-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageresult',
            name='foreign_key',
        ),
        migrations.AddField(
            model_name='imageresult',
            name='img_search_key',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='image.ImageSearch'),
        ),
    ]
