# Generated by Django 2.1.2 on 2019-02-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20190204_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesearch',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
