# Generated by Django 2.1.2 on 2019-02-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20190204_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresult',
            name='score',
            field=models.FloatField(),
        ),
    ]
