# Generated by Django 2.1.2 on 2019-02-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20190204_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresult',
            name='img_search_key',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='image.ImageSearch'),
        ),
    ]
